[versions]
commons_io = "2.11.0"
download_task = "4.1.1"
guava = "31.1-jre"
jackson_xml = "2.14.1"
launchermeta_parser = "1.0.0"
enigma = "1.8.6"
enigma_plugin = "1.3.1"
tiny_remapper = "0.7.2"
stitch = "0.6.1"
unpick = "3.0.6"
mapping_io = "0.3.0"
javadoc_draftsman = "1.2.2"

fabric_loader = "0.14.11"
jetbrains_annotations = "23.0.0"
jsr305 = "3.0.2"
gson = "2.9.1"
netty = "4.1"

quiltflower = "1.10.0-20230120.185555-31"
cfr = "0.2.0"

junit = "5.9.1"
proguard = "7.3.0"

[libraries]
commons_io = { module = "commons-io:commons-io", version.ref = "commons_io" }
download_task = { module = "de.undercouch:gradle-download-task", version.ref = "download_task" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jackson_xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson_xml" }
launchermeta_parser = { module = "org.quiltmc:launchermeta-parser", version.ref = "launchermeta_parser" }

enigma = { module = "org.quiltmc:enigma", version.ref = "enigma" }
enigma_cli = { module = "org.quiltmc:enigma-cli", version.ref = "enigma" }
enigma_swing = { module = "org.quiltmc:enigma-swing", version.ref = "enigma" }
enigma_plugin = { module = "org.quiltmc:quilt-enigma-plugin", version.ref = "enigma_plugin" }
tiny_remapper = { module = "org.quiltmc:tiny-remapper", version.ref = "tiny_remapper" }
stitch = { module = "net.fabricmc:stitch", version.ref = "stitch" }
unpick = { module = "org.quiltmc.unpick:unpick", version.ref = "unpick" }
unpick_cli = { module = "org.quiltmc.unpick:unpick-cli", version.ref = "unpick" }
unpick_format_utils = { module = "org.quiltmc.unpick:unpick-format-utils", version.ref = "unpick" }
mapping_io = { module = "net.fabricmc:mapping-io", version.ref = "mapping_io" }
javadoc_draftsman = { module = "org.quiltmc:javadoc-draftsman", version.ref = "javadoc_draftsman" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }

# Decompilers
cfr = { module = "net.fabricmc:cfr", version.ref = "cfr" }
quiltflower = { module = "org.quiltmc:quiltflower", version.ref = "quiltflower" }

# Testing
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
proguard = { module = "com.guardsquare:proguard-base", version.ref = "proguard" }

[bundles]
enigma_full = ["enigma", "enigma_cli", "enigma_swing", "enigma_plugin"]
unpick_full = ["unpick", "unpick_cli", "unpick_format_utils"]
