name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [17, 19]
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build javadocJar --stacktrace
      - name: Build artifacts
        if: ${{ matrix.java == 17 }}
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
      - run: ./gradlew decompileQuiltflower decompileTargetQuiltflower --stacktrace
      - name: Check Target Decompiled
        id: can-create-diff
        uses: andstor/file-existence-action@v2
        with:
          files: "namedSrc/net/minecraft/client/main/Main.java"
      - name: Create diff
        if: steps.can-create-diff.outputs.files_exists == 'true'
        run: diff -bur namedTargetSrc/ namedSrc/ > target.diff
      - name: Upload diff
        if: steps.can-create-diff.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: Diff
          path: target.diff
